spring.application.name=ProductCatalogService_Feb2026

logging.level.org.springframework.security=trace

# db specific
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/productcatalogservice_feb2026
spring.datasource.username=root
spring.datasource.password=12345
